Guard support SearchView
Fix issue #167 by keeping class SearchView

Otherwise `(SearchView) MenuItemCompat.getActionView(menuItem)` returns
and this causes:

06-30 20:08:33.553  20810-20810/com.artemzin.android.wail
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.artemzin.android.wail, PID: 20810
    java.lang.NullPointerException: Attempt to invoke virtual method
'android.view.View android.view.View.findViewById(int)' on a null
object reference
            at
com.artemzin.android.wail.ui.fragment.main.TracksListFragment$TracksSear
chHandler.setSearchItem(TracksListFragment.java:417)